#!/usr/bin/env bash
#using while loop
COUNTER=1
while [ "$COUNTER" -le 10 ];
do
if [ "$COUNTER" -eq 4 ];
then
echo "bad luck"
elif [ "$COUNTER" -eq 8 ];
then
echo "good luck"
else
echo "Holberton School"
fi
COUNTER=$(( COUNTER + 1 ))
done
