#!/usr/bin/env bash
#using if/else loop
F="holbertonschool"
if [ -e "$F" ];
then
echo "$F file exists"
if [ -s "$F" ];
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f "$F" ];
then
echo "holbertonschool is a regular file"
fi
else
echo "holbertonschool file does not exist"
fi
