#!/usr/bin/env bash
#get Apache to run on the container and to return a page containing Hello Holberton
apt-get install apache2 -y
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf